package com.github.uniqueT.webAuto.event.invoke;

import java.io.Serializable;
import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Method;

/**
 * Serializable function interface of cases, to provide lambda object generated in the JVM
 * @author uniqueT
 *
 */
public interface CaseSerializable extends Serializable {
	
	/**
	 * get lambda object generated in the JVM
	 * @return lambda object, it will be a lambda implementation of a case's method
	 * @throws Exception if any exceptions thrown here, framework must solve it
	 */
	default SerializedLambda getSerializedLambda() throws Exception {
		//this is an internal method generated by JVM
        Method method = getClass().getDeclaredMethod("writeReplace");
        method.setAccessible(true);
        return (SerializedLambda) method.invoke(this);
    }

}
